spring.cloud.stream.kafka.streams.binder:
  brokers:
    - localhost:9092
  configuration:
    application.id: fallou-cloud-15
    schema.registry.url: http://localhost:8081
    commit.interval.mms: 1000
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde

spring.cloud.stream.bindings.jobDescProcessing-in-0:
  destination: person-job

spring.cloud.stream.bindings.jobDescProcessing-in-1:
  destination: kafka_tr_db.kafka_tr_db.t_job_desc

spring.cloud.stream.bindings.jobDescProcessing-out-0:
  destination: person-job-stat

spring.cloud.stream.kafka.streams.bindings.input:
  consumer:
    startOffset: latest
    keySerde  : org.apache.kafka.common.serialization.Serdes$StringSerde
    valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
#  producer:
#    #    keySerde  : org.apache.kafka.common.serialization.Serdes$StringSerde
#    keySerde  : org.apache.kafka.common.serialization.Serdes$StringSerde
#    valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde