/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mycorp.mynamespace;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Sample schema to help you get started. */
@org.apache.avro.specific.AvroGenerated
public class JobStat extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8142932988106688567L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"JobStat\",\"namespace\":\"com.mycorp.mynamespace\",\"doc\":\"Sample schema to help you get started.\",\"fields\":[{\"name\":\"count\",\"type\":\"int\"},{\"name\":\"jobName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"description\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<JobStat> ENCODER =
      new BinaryMessageEncoder<JobStat>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<JobStat> DECODER =
      new BinaryMessageDecoder<JobStat>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<JobStat> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<JobStat> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<JobStat>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this JobStat to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a JobStat from a ByteBuffer. */
  public static JobStat fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int count;
  @Deprecated public java.lang.String jobName;
  @Deprecated public java.lang.String description;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public JobStat() {}

  /**
   * All-args constructor.
   * @param count The new value for count
   * @param jobName The new value for jobName
   * @param description The new value for description
   */
  public JobStat(java.lang.Integer count, java.lang.String jobName, java.lang.String description) {
    this.count = count;
    this.jobName = jobName;
    this.description = description;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return count;
    case 1: return jobName;
    case 2: return description;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: count = (java.lang.Integer)value$; break;
    case 1: jobName = (java.lang.String)value$; break;
    case 2: description = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'count' field.
   * @return The value of the 'count' field.
   */
  public java.lang.Integer getCount() {
    return count;
  }

  /**
   * Sets the value of the 'count' field.
   * @param value the value to set.
   */
  public void setCount(java.lang.Integer value) {
    this.count = value;
  }

  /**
   * Gets the value of the 'jobName' field.
   * @return The value of the 'jobName' field.
   */
  public java.lang.String getJobName() {
    return jobName;
  }

  /**
   * Sets the value of the 'jobName' field.
   * @param value the value to set.
   */
  public void setJobName(java.lang.String value) {
    this.jobName = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.String value) {
    this.description = value;
  }

  /**
   * Creates a new JobStat RecordBuilder.
   * @return A new JobStat RecordBuilder
   */
  public static com.mycorp.mynamespace.JobStat.Builder newBuilder() {
    return new com.mycorp.mynamespace.JobStat.Builder();
  }

  /**
   * Creates a new JobStat RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new JobStat RecordBuilder
   */
  public static com.mycorp.mynamespace.JobStat.Builder newBuilder(com.mycorp.mynamespace.JobStat.Builder other) {
    return new com.mycorp.mynamespace.JobStat.Builder(other);
  }

  /**
   * Creates a new JobStat RecordBuilder by copying an existing JobStat instance.
   * @param other The existing instance to copy.
   * @return A new JobStat RecordBuilder
   */
  public static com.mycorp.mynamespace.JobStat.Builder newBuilder(com.mycorp.mynamespace.JobStat other) {
    return new com.mycorp.mynamespace.JobStat.Builder(other);
  }

  /**
   * RecordBuilder for JobStat instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<JobStat>
    implements org.apache.avro.data.RecordBuilder<JobStat> {

    private int count;
    private java.lang.String jobName;
    private java.lang.String description;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mycorp.mynamespace.JobStat.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.count)) {
        this.count = data().deepCopy(fields()[0].schema(), other.count);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.jobName)) {
        this.jobName = data().deepCopy(fields()[1].schema(), other.jobName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing JobStat instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mycorp.mynamespace.JobStat other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.count)) {
        this.count = data().deepCopy(fields()[0].schema(), other.count);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.jobName)) {
        this.jobName = data().deepCopy(fields()[1].schema(), other.jobName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'count' field.
      * @return The value.
      */
    public java.lang.Integer getCount() {
      return count;
    }

    /**
      * Sets the value of the 'count' field.
      * @param value The value of 'count'.
      * @return This builder.
      */
    public com.mycorp.mynamespace.JobStat.Builder setCount(int value) {
      validate(fields()[0], value);
      this.count = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'count' field has been set.
      * @return True if the 'count' field has been set, false otherwise.
      */
    public boolean hasCount() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'count' field.
      * @return This builder.
      */
    public com.mycorp.mynamespace.JobStat.Builder clearCount() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'jobName' field.
      * @return The value.
      */
    public java.lang.String getJobName() {
      return jobName;
    }

    /**
      * Sets the value of the 'jobName' field.
      * @param value The value of 'jobName'.
      * @return This builder.
      */
    public com.mycorp.mynamespace.JobStat.Builder setJobName(java.lang.String value) {
      validate(fields()[1], value);
      this.jobName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'jobName' field has been set.
      * @return True if the 'jobName' field has been set, false otherwise.
      */
    public boolean hasJobName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'jobName' field.
      * @return This builder.
      */
    public com.mycorp.mynamespace.JobStat.Builder clearJobName() {
      jobName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.String getDescription() {
      return description;
    }

    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public com.mycorp.mynamespace.JobStat.Builder setDescription(java.lang.String value) {
      validate(fields()[2], value);
      this.description = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public com.mycorp.mynamespace.JobStat.Builder clearDescription() {
      description = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public JobStat build() {
      try {
        JobStat record = new JobStat();
        record.count = fieldSetFlags()[0] ? this.count : (java.lang.Integer) defaultValue(fields()[0]);
        record.jobName = fieldSetFlags()[1] ? this.jobName : (java.lang.String) defaultValue(fields()[1]);
        record.description = fieldSetFlags()[2] ? this.description : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<JobStat>
    WRITER$ = (org.apache.avro.io.DatumWriter<JobStat>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<JobStat>
    READER$ = (org.apache.avro.io.DatumReader<JobStat>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
