/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mycorp.mynamespace;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Sample schema to help you get started. */
@org.apache.avro.specific.AvroGenerated
public class PersonJob extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7309467335502123592L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PersonJob\",\"namespace\":\"com.mycorp.mynamespace\",\"doc\":\"Sample schema to help you get started.\",\"fields\":[{\"name\":\"personName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"jobName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PersonJob> ENCODER =
      new BinaryMessageEncoder<PersonJob>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PersonJob> DECODER =
      new BinaryMessageDecoder<PersonJob>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<PersonJob> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<PersonJob> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PersonJob>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this PersonJob to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a PersonJob from a ByteBuffer. */
  public static PersonJob fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String personName;
  @Deprecated public java.lang.String jobName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PersonJob() {}

  /**
   * All-args constructor.
   * @param personName The new value for personName
   * @param jobName The new value for jobName
   */
  public PersonJob(java.lang.String personName, java.lang.String jobName) {
    this.personName = personName;
    this.jobName = jobName;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return personName;
    case 1: return jobName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: personName = (java.lang.String)value$; break;
    case 1: jobName = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'personName' field.
   * @return The value of the 'personName' field.
   */
  public java.lang.String getPersonName() {
    return personName;
  }

  /**
   * Sets the value of the 'personName' field.
   * @param value the value to set.
   */
  public void setPersonName(java.lang.String value) {
    this.personName = value;
  }

  /**
   * Gets the value of the 'jobName' field.
   * @return The value of the 'jobName' field.
   */
  public java.lang.String getJobName() {
    return jobName;
  }

  /**
   * Sets the value of the 'jobName' field.
   * @param value the value to set.
   */
  public void setJobName(java.lang.String value) {
    this.jobName = value;
  }

  /**
   * Creates a new PersonJob RecordBuilder.
   * @return A new PersonJob RecordBuilder
   */
  public static com.mycorp.mynamespace.PersonJob.Builder newBuilder() {
    return new com.mycorp.mynamespace.PersonJob.Builder();
  }

  /**
   * Creates a new PersonJob RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PersonJob RecordBuilder
   */
  public static com.mycorp.mynamespace.PersonJob.Builder newBuilder(com.mycorp.mynamespace.PersonJob.Builder other) {
    return new com.mycorp.mynamespace.PersonJob.Builder(other);
  }

  /**
   * Creates a new PersonJob RecordBuilder by copying an existing PersonJob instance.
   * @param other The existing instance to copy.
   * @return A new PersonJob RecordBuilder
   */
  public static com.mycorp.mynamespace.PersonJob.Builder newBuilder(com.mycorp.mynamespace.PersonJob other) {
    return new com.mycorp.mynamespace.PersonJob.Builder(other);
  }

  /**
   * RecordBuilder for PersonJob instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PersonJob>
    implements org.apache.avro.data.RecordBuilder<PersonJob> {

    private java.lang.String personName;
    private java.lang.String jobName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mycorp.mynamespace.PersonJob.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.personName)) {
        this.personName = data().deepCopy(fields()[0].schema(), other.personName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.jobName)) {
        this.jobName = data().deepCopy(fields()[1].schema(), other.jobName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PersonJob instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mycorp.mynamespace.PersonJob other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.personName)) {
        this.personName = data().deepCopy(fields()[0].schema(), other.personName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.jobName)) {
        this.jobName = data().deepCopy(fields()[1].schema(), other.jobName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'personName' field.
      * @return The value.
      */
    public java.lang.String getPersonName() {
      return personName;
    }

    /**
      * Sets the value of the 'personName' field.
      * @param value The value of 'personName'.
      * @return This builder.
      */
    public com.mycorp.mynamespace.PersonJob.Builder setPersonName(java.lang.String value) {
      validate(fields()[0], value);
      this.personName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'personName' field has been set.
      * @return True if the 'personName' field has been set, false otherwise.
      */
    public boolean hasPersonName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'personName' field.
      * @return This builder.
      */
    public com.mycorp.mynamespace.PersonJob.Builder clearPersonName() {
      personName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'jobName' field.
      * @return The value.
      */
    public java.lang.String getJobName() {
      return jobName;
    }

    /**
      * Sets the value of the 'jobName' field.
      * @param value The value of 'jobName'.
      * @return This builder.
      */
    public com.mycorp.mynamespace.PersonJob.Builder setJobName(java.lang.String value) {
      validate(fields()[1], value);
      this.jobName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'jobName' field has been set.
      * @return True if the 'jobName' field has been set, false otherwise.
      */
    public boolean hasJobName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'jobName' field.
      * @return This builder.
      */
    public com.mycorp.mynamespace.PersonJob.Builder clearJobName() {
      jobName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PersonJob build() {
      try {
        PersonJob record = new PersonJob();
        record.personName = fieldSetFlags()[0] ? this.personName : (java.lang.String) defaultValue(fields()[0]);
        record.jobName = fieldSetFlags()[1] ? this.jobName : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PersonJob>
    WRITER$ = (org.apache.avro.io.DatumWriter<PersonJob>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PersonJob>
    READER$ = (org.apache.avro.io.DatumReader<PersonJob>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
